version: '3'
services:
  nanonode:
    image: "gcr.io/raidots-190218/github-rawrmaan-nano-node-proxy:master"
    restart: "unless-stopped"
    ports:
     - "80:80"
  watchtower:
    image: "v2tec/watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
