version: '3'
services:
  nanonode:
    image: "gcr.io/raidots-190218/github-rawrmaan-raiblocks-node-docker-easy:master"
    restart: "unless-stopped"
    ports:
     - "7075:7075/udp"
     - "7075:7075"
     - "::1:7076:7076"
     - "80:80"
     - "::1:80:80"
    volumes:
     - "~:/root"
  watchtower:
    image: "v2tec/watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      