version: '3'
services:
  nanoproxy:
    image: "gcr.io/raidots-190218/github-rawrmaan-nano-node-proxy:master"
    restart: "unless-stopped"
    ports:
      - "80"
    env_file:
      - /opt/proxy.env
    volumes:
     - "~/app:/usr/src/app/env"
  watchtower:
    image: "v2tec/watchtower"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
